name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - name: Build
        run: go build -v ./core/...

      - name: Test
        run: go test -v ./core/...
